author: Raniy
database: false
description: "Provides an easy, permission controlled, highly configurable method to flip a players gamemode."
main: me.raniy.plugins.TGM.TGM
name: TGM
startup: postworld
url:
version: v1.6
commands:
    togglegamemode:
        description: Flips you from one gamemode to the other
        usage: |
            /togglegamemode 
    tgm:
        description: Flips you from one gamemode to the other
        usage: |
            /tgm
            